version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data/storage:/qdrant/storage
    restart: unless-stopped
